ci:
  skip: [bandit]

repos:
- repo: https://github.com/pycqa/flake8
  rev: 7.1.0
  hooks:
  - id: flake8
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks:
  - id: bandit
    args: ["--configfile=pyproject.toml"]
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
